import type { Product } from '@entities/product';

export const PRODUCTS: Product[] = [
	{
		id: 1,
		category: 'Зефир',
		name: 'Зефир 1',
		price: 500,
		weight: 250,
		description: 'Описание продукции, несколько строк',
		isPopular: false,
		isUnique: true,
		imgSrc: '/demo/marmelad/images/zefir-1.png',
	},
	{
		id: 2,
		category: 'Зефир',
		name: 'Зефир 2',
		price: 500,
		weight: 250,
		description: 'Описание продукции, несколько строк',
		isPopular: true,
		isUnique: false,
		imgSrc: '/demo/marmelad/images/zefir-2.png',
	},
	{
		id: 3,
		category: 'Зефир',
		name: 'Зефир 3',
		price: 500,
		weight: 250,
		description: 'Описание продукции, несколько строк',
		isPopular: true,
		isUnique: false,
		imgSrc: '/demo/marmelad/images/zefir-3.png',
	},
	{
		id: 4,
		category: 'Зефир',
		name: 'Зефир 4',
		price: 500,
		weight: 250,
		description: 'Описание продукции, несколько строк',
		isPopular: false,
		isUnique: true,
		imgSrc: '/demo/marmelad/images/zefir-4.png',
	},
	{
		id: 5,
		category: 'Рахат-Лукум',
		name: 'Рахат-Лукум 1',
		price: 600,
		weight: 400,
		description: 'Описание продукции, несколько строк',
		isPopular: true,
		isUnique: false,
		imgSrc: '/demo/marmelad/images/rahat-1.png',
	},
	{
		id: 6,
		category: 'Рахат-Лукум',
		name: 'Рахат-Лукум 2',
		price: 600,
		weight: 400,
		description: 'Описание продукции, несколько строк',
		isPopular: false,
		isUnique: true,
		imgSrc: '/demo/marmelad/images/rahat-2.png',
	},
	{
		id: 7,
		category: 'Рахат-Лукум',
		name: 'Рахат-Лукум 3',
		price: 600,
		weight: 400,
		description: 'Описание продукции, несколько строк',
		isPopular: false,
		isUnique: true,
		imgSrc: '/demo/marmelad/images/rahat-3.png',
	},
	{
		id: 8,
		category: 'Рахат-Лукум',
		name: 'Рахат-Лукум 4',
		price: 600,
		weight: 400,
		description: 'Описание продукции, несколько строк',
		isPopular: true,
		isUnique: false,
		imgSrc: '/demo/marmelad/images/rahat-4.png',
	},
	{
		id: 9,
		category: 'Конфеты',
		name: 'Конфеты 1',
		price: 400,
		weight: 800,
		description: 'Описание продукции, несколько строк',
		isPopular: false,
		isUnique: true,
		imgSrc: '/demo/marmelad/images/conf-2.png',
	},
	{
		id: 10,
		category: 'Конфеты',
		name: 'Конфеты 2',
		price: 400,
		weight: 800,
		description: 'Описание продукции, несколько строк',
		isPopular: true,
		isUnique: false,
		imgSrc: '/demo/marmelad/images/conf-2.png',
	},
];
