import type { Product } from '@entities/product';

export const PRODUCTS: Product[] = [
	{
		id: 1,
		category: 'Зефир',
		name: 'Зефир 1',
		price: 500,
		weight: 250,
		description: 'Описание продукции, несколько строк',
		isPopular: false,
		isUnique: true,
		imgSrc: '',
	},
	{
		id: 2,
		category: 'Зефир',
		name: 'Зефир 2',
		price: 500,
		weight: 250,
		description: 'Описание продукции, несколько строк',
		isPopular: true,
		isUnique: false,
		imgSrc: '',
	},
	{
		id: 3,
		category: 'Зефир',
		name: 'Зефир 3',
		price: 500,
		weight: 250,
		description: 'Описание продукции, несколько строк',
		isPopular: true,
		isUnique: true,
		imgSrc: '',
	},
	{
		id: 4,
		category: 'Рахат-Лукум',
		name: 'Рахат-Лукум 1',
		price: 600,
		weight: 400,
		description: 'Описание продукции, несколько строк',
		isPopular: true,
		isUnique: true,
		imgSrc: '',
	},
	{
		id: 5,
		category: 'Рахат-Лукум',
		name: 'Рахат-Лукум 2',
		price: 600,
		weight: 400,
		description: 'Описание продукции, несколько строк',
		isPopular: true,
		isUnique: false,
		imgSrc: '',
	},
	{
		id: 6,
		category: 'Рахат-Лукум',
		name: 'Рахат-Лукум 3',
		price: 600,
		weight: 400,
		description: 'Описание продукции, несколько строк',
		isPopular: true,
		isUnique: true,
		imgSrc: '',
	},
	{
		id: 7,
		category: 'Конфеты',
		name: 'Конфеты 1',
		price: 400,
		weight: 800,
		description: 'Описание продукции, несколько строк',
		isPopular: false,
		isUnique: true,
		imgSrc: '',
	},
	{
		id: 8,
		category: 'Конфеты',
		name: 'Конфеты 2',
		price: 400,
		weight: 800,
		description: 'Описание продукции, несколько строк',
		isPopular: true,
		isUnique: true,
		imgSrc: '',
	},
	{
		id: 9,
		category: 'Конфеты',
		name: 'Конфеты 3',
		price: 400,
		weight: 800,
		description: 'Описание продукции, несколько строк',
		isPopular: false,
		isUnique: true,
		imgSrc: '',
	},
	{
		id: 10,
		category: 'Конфеты',
		name: 'Конфеты 4',
		price: 400,
		weight: 800,
		description: 'Описание продукции, несколько строк',
		isPopular: false,
		isUnique: true,
		imgSrc: '',
	},
];
